var titleList={
	"www.baidu.com": "百度一下，你就知道",
	"www.google.com": "Google",
	"www.zhihu.com": "知乎",
	"www.bilibili.com": "哔哩哔哩弹幕视频网 - ( ゜- ゜)つロ 乾杯~ - bilibili",
	"www.amazon.cn": "亚马逊",
	"movie.douban.com": "豆瓣电影",
	"tieba.baidu.com": "百度贴吧",
	"baike.baidu.com": "百度百科",
	"pt.vm.fudan.edu.cn": "复旦PT",
	"www.lagou.com": "找工作-互联网招聘求职网-拉勾网",
	"mail.google.com": "Gmail",
	"store.steampowered.com": "欢迎来到 Steam",
	"detail.tmall.com": "天猫",
	"zhidao.baidu.com": "百度知道",
	"kat.cr": "KAT - Kickass Torrents",
	"github.com": "Github",
	"list.tmall.com": "尚天猫，就购了",
	"www.sonkwo.com": "杉果游戏",
	"www.gamersky.com": "游民星空 GamerSky.com",
	"s.taobao.com": "淘宝搜索",
	"www.douyutv.com": "炉石传说",
	"stackoverflow.com": "Stack Overflow",
	"www.douban.com": "豆瓣",
	"weibo.com": "新浪微博",
	"pan.baidu.com": "百度盘",
	"waimai.baidu.com": "百度外卖",
	"cashiergtj.alipay.com": "支付宝 - 网上支付 安全快速！",
	"steamcommunity.com": "Steam 社区",
	"bbs.fudan.edu.cn": "精华区文章阅读 - 日月光华",
	"vdisk.weibo.com": "我的微盘-微盘",
	"reactjs.cn": "React",
	"chrome.google.com": "开发者信息中心 - Chrome 网上应用店",
	"115.com": "115",
	"www.w3school.com.cn": "w3school",
	"www.smzdm.com": "什么值得买 | 品质消费第一站_网购决策中立门户",
	"www.ituring.com.cn": "图灵社区",
	"segmentfault.com": "SegmentFault",
	"zh.wikipedia.org": "维基百科，自由的百科全书",
	"login.taobao.com": "淘宝网 - 淘！我喜欢",
	"image.baidu.com": "百度图片搜索",
	"excashier.alipay.com": "支付宝 - 网上支付 安全快速！",
	"talent.baidu.com": "百度校园招聘",
	"zh.coursera.org": "coursera",
	"pc.tgbus.com": "巴士单机游戏 PC.TGBUS.COM",
	"bbs.3dmgame.com": "3DMGAME论坛",
	"note.wiz.cn": "WizNote",
	"www.gewara.com": "格瓦拉生活网",
	"www.renji.com": "上海交通大学医学院附属 仁济医院",
	"v2.bootcss.com": "Bootstrap",
	"search.smzdm.com": "forever_优惠精选_什么值得买",
	"www.iqiyi.com": "爱奇艺",
	"zhifu.baidu.com": "百度钱包收银台",
	"www.forever21.cn": "Forever21.cn - FOREVER21",
	"terraria.gamepedia.com": "Welcome to the Official Terraria Wiki",
	"elearning.fudan.edu.cn": "eLearning : 首页 : 欢迎",
	"book.douban.com": "豆瓣图书",
	"tv.sohu.com": "搜狐视频",
	"login.sina.com.cn": "Sina Passport",
	"www.dell.com": "Dell",
	"www.renren.com": "人人网 ",
	"www.portal.fudan.edu.cn": "复旦大学校园信息门户",
	"www.coursera.org": "Coursera：一流大学免费在线课程平台 | Coursera",
	"scholar.google.com": "antony and cleopatra character analysis - Google 学术搜索",
	"mail.163.com": "163邮箱",
	"www.sogou.com": "搜狗",
	"developer.mozilla.org": "MDN",
	"mail.fudan.edu.cn": "复旦邮箱",
	"en.wikipedia.org": "Wikipedia, the free encyclopedia",
	"bbs.hearthstone.com.cn": "《炉石传说》官方论坛",
	"v3.bootcss.com": "Bootstrap",
	"item.taobao.com": "淘宝网",
	"www.amazon.com": "Amazon",
	"apply.decisiondesk.co.uk": "The Rhodes Scholarship",
	"wulin.fhyx.com": "《侠客风云传》官网_原《新武林群侠传》官方网站_2015经典再现",
	"www.career.fudan.edu.cn": "复旦大学学生职业发展教育服务中心",
	"zu.sh.fang.com": "【上海租房信息_房屋出租】- 搜房网",
	"join.qq.com": "Tencent 校园招聘",
	"music.baidu.com": "百度音乐",
	"trade.tmall.com": "Tmall.com天猫",
	"www.shixiseng.com": "找实习-实习列表-实习僧-实习生-最靠谱的实习生招聘网站",
	"buy.taobao.com": "淘宝网 - 淘！我喜欢",
	"ele.me": "饿了么",
	"www.npmjs.com": "gulp-minify-css",
	"www.taobao.com": "淘宝网",
	"www.0daydown.com": "0DayDown | 0天与您关注资讯",
	"cloud.digitalocean.com": "DigitalOcean Control Panel",
	"www.12306.cn": "铁路客户服务中心",
	"luoqi.tiancity.com": "《洛奇Mabinogi》官方网站",
	"fuge.bearychat.com": "复歌科技",
	"www.easyulife.com": "www.easyulife.com|简单你的生活",
	"webmap0.map.bdimg.com": "thumbnails (218×140)",
	"www.115.com": "115，全新的生活方式！",
	"creditcard.ccb.com": "信用卡主页_中国建设银行",
	"www.acfun.tv": "Acfun",
	"www.youtube.com": "YouTube",
	"www.cnki.net": "中国知网",
	"map.baidu.com": "百度地图",
	"www.microsoft.com": "Microsoft",
	"www.facebook.com": "Facebook",
	"www.tudou.com": "土豆网",
	"www.baixing.com": "百姓网",
	"www.ximalaya.com": "喜马拉雅FM",
	"www.urp.fudan.edu.cn": "学工管理系统",
	"mail.qq.com": "QQ邮箱",
	"open.163.com": "TED_网易公开课",
	"www.ccb.com": "欢迎访问中国建设银行网站-个人客户",
	"www.bootcss.com": "Bootstrap中文网",
	"weixin.qq.com": "微信，是一个生活方式",
	"www.dropbox.com": "主页 - Dropbox",
	"www.urp.fudan.edu.cn": "复旦大学URP信息化校园应用系统",
	"www.dianping.com": "大众点评网",
	"www.jd.com": "京东(JD.COM)-综合网购首选-正品低价、品质保障、配送及时、轻松购物！",
	"www.quora.com": "Home - Quora",
	"www.163.com": "网易",
	"www.sina.com.cn": "新浪首页",
	"subom.net": "中文字幕下载 | 字幕下载 | 电影字幕 | 外挂字幕 | Sub of Movies.",
	"exmail.qq.com": "腾讯企业邮箱，用心你看得见 - 热线：400-100-3366",
}