var titleList={
	"www.baidu.com": "百度一下，你就知道",
	"www.google.com": "Google",
	"www.zhihu.com": "知乎",
	"www.bilibili.com": "哔哩哔哩弹幕视频网 - ( ゜- ゜)つロ 乾杯~ - bilibili",
	"www.amazon.cn": "亚马逊",
	"movie.douban.com": "豆瓣电影",
	"tieba.baidu.com": "百度贴吧",
	"baike.baidu.com": "百度百科",
	"pt.vm.fudan.edu.cn": "复旦PT",
	"www.lagou.com": "找工作-互联网招聘求职网-拉勾网",
	"mail.google.com": "Gmail",
	"store.steampowered.com": "欢迎来到 Steam",
	"detail.tmall.com": "天猫",
	"zhidao.baidu.com": "百度知道",
	"kat.cr": "KAT - Kickass Torrents",
	"github.com": "Github",
	"list.tmall.com": "尚天猫，就购了",
	"www.sonkwo.com": "杉果游戏",
	"www.gamersky.com": "游民星空 GamerSky.com",
	"s.taobao.com": "淘宝搜索",
	"www.douyutv.com": "炉石传说",
	"stackoverflow.com": "Stack Overflow",
	"www.douban.com": "豆瓣",
	"weibo.com": "新浪微博",
	"pan.baidu.com": "百度盘",
	"waimai.baidu.com": "百度外卖",
	"cashiergtj.alipay.com": "支付宝 - 网上支付 安全快速！",
	"steamcommunity.com": "Steam 社区",
	"bbs.fudan.edu.cn": "精华区文章阅读 - 日月光华",
	"vdisk.weibo.com": "我的微盘-微盘",
	"reactjs.cn": "React",
	"chrome.google.com": "开发者信息中心 - Chrome 网上应用店",
	"115.com": "115",
	"www.w3school.com.cn": "w3school",
	"www.smzdm.com": "什么值得买 | 品质消费第一站_网购决策中立门户",
	"www.ituring.com.cn": "图灵社区",
	"segmentfault.com": "SegmentFault",
	"zh.wikipedia.org": "维基百科，自由的百科全书",
	"login.taobao.com": "淘宝网 - 淘！我喜欢",
	"image.baidu.com": "百度图片搜索",
	"excashier.alipay.com": "支付宝 - 网上支付 安全快速！",
	"talent.baidu.com": "百度校园招聘",
	"zh.coursera.org": "coursera",
	"pc.tgbus.com": "巴士单机游戏 PC.TGBUS.COM",
	"bbs.3dmgame.com": "3DMGAME论坛",
	"note.wiz.cn": "WizNote",
	"www.gewara.com": "格瓦拉生活网",
	"www.renji.com": "上海交通大学医学院附属 仁济医院",
	"v2.bootcss.com": "Bootstrap",
	"search.smzdm.com": "forever_优惠精选_什么值得买",
	"www.iqiyi.com": "爱奇艺",
	"zhifu.baidu.com": "百度钱包收银台",
	"www.forever21.cn": "Forever21.cn - FOREVER21",
	"terraria.gamepedia.com": "Welcome to the Official Terraria Wiki",
	"elearning.fudan.edu.cn": "eLearning : 首页 : 欢迎",
	"book.douban.com": "豆瓣图书",
	"tv.sohu.com": "搜狐视频",
	"login.sina.com.cn": "Sina Passport",
	"www.dell.com": "Dell",
	"www.renren.com": "人人网 ",
	"www.portal.fudan.edu.cn": "复旦大学校园信息门户",
	"www.coursera.org": "Coursera：一流大学免费在线课程平台 | Coursera",
	"scholar.google.com": "antony and cleopatra character analysis - Google 学术搜索",
	"mail.163.com": "163邮箱",
	"www.sogou.com": "搜狗",
	"developer.mozilla.org": "MDN",
	"mail.fudan.edu.cn": "复旦邮箱",
	"en.wikipedia.org": "Wikipedia, the free encyclopedia",
	"bbs.hearthstone.com.cn": "《炉石传说》官方论坛",
	"v3.bootcss.com": "Bootstrap",
	"item.taobao.com": "淘宝网",
	"www.amazon.com": "Amazon",
	"apply.decisiondesk.co.uk": "The Rhodes Scholarship",
	"wulin.fhyx.com": "《侠客风云传》官网_原《新武林群侠传》官方网站_2015经典再现",
	"www.career.fudan.edu.cn": "复旦大学学生职业发展教育服务中心",
	"s.weibo.com": "微博搜索 - 压寨果子 - 微博",
	"game.ali213.net": "Braid/时空幻境深入剧情分析 - 黑白雨夜+雷电4：赶尽杀绝+超级棒球：加时赛+速度2X+Feist+破碎大陆：年度版+灵魂：生命之息+下落英雄HD+邮递大师模拟+王国传说+血浴+岛屿部落5 - 游侠NETSHOW论坛 - Powered by Discuz!",
	"zu.sh.fang.com": "【上海租房信息_房屋出租】- 搜房网",
	"webmap1.map.bdimg.com": "thumbnails (228×138)",
	"join.qq.com": "软件开发-Web前端开发方向 | Tencent 校园招聘",
	"music.baidu.com": "TFBOYS的歌曲,TFBOYS的专辑,TFBOYS最好听的歌_百度音乐-听到极致",
	"trade.tmall.com": "确认收货 - Tmall.com天猫",
	"www.shixiseng.com": "找实习-实习列表-实习僧-实习生-最靠谱的实习生招聘网站",
	"www.browsersync.cn": "",
	"localhost": "phpMyAdmin 2.10.3 - localhost",
	"buy.taobao.com": "淘宝网 - 淘！我喜欢",
	"tanbowensg.github.io": "Simple",
	"ele.me": "记得回来点单哦！ - 饿了么",
	"www.w3schools.com": "HTML iframe sandbox Attribute",
	"www.jwc.fudan.edu.cn": "关于做好2015年中秋节和国庆节放假教学工作调整安排的通知",
	"club.jd.com": "TENGA男性自慰器：“太小了，真的插不进去，做工一般，不值这么多钱......” - 京东",
	"www.npmjs.com": "gulp-minify-css",
	"muji.tmall.com": "首页-无印良品MUJI官方旗舰店-天猫Tmall.com",
	"www.ali213.net": "鬼泣4特别版_鬼泣4特别版中文版下载_汉化_补丁_攻略_专题_游侠网",
	"accounts.google.com": "登录 - Google 帐户",
	"tanbowensg.me": "Index of /",
	"haitao.smzdm.com": "美亚/德亚闪电特价：Diesel 平角内裤、Herschel 双肩包、Versace 女款腕表、美津浓 预言4顶级跑鞋 9月8日24点更新_美国亚马逊_每日更新_海淘专区_什么值得买",
	"www.taobao.com": "淘宝网",
	"forums.fedoraforum.org": "Fedora 19 won't configure Intel Wireless 7260 (rev 6b) device ... - FedoraForum.org",
	"ba.stagging.fugetech.com": "login",
	"passport.115.com": "",
	"zhaopin.yhd.com": "网上超市1号店，省力省钱省时间",
	"imagedecode.com": "ImageDecode.com|Earn money sharing images",
	"www.mfjb.top": "日本tenga异次元手提式飞机杯 - 「一起来买飞机杯」",
	"www.0daydown.com": "0DayDown | 0天与您关注资讯",
	"www.ujianli.com": "优简历网-个人简历_简历模板_简历评测_简历怎么写_免费写简历",
	"safe.jd.com": "找回密码",
	"class.coursera.org": "Coursera",
	"www.shmoop.com": "The Tragedy of Antony and Cleopatra Characters",
	"techshow.ctrip.com": "携程技术校园招聘",
	"facebook.github.io": "Flux | Application Architecture for Building User Interfaces",
	"cloud.digitalocean.com": "DigitalOcean Control Panel",
	"www.typorganism.com": "ASCII-O-Matic : Generate HTML",
	"chrome.liuyixi.com": "概述 - chrome插件中文开发文档(非官方)",
	"cashier.jd.com": "京东收银台-支付结果",
	"s3.pdim.gs": "",
	"webmap2.map.bdimg.com": "thumbnails (228×138)",
	"www.urp.fudan.edu.cn:84": "复旦大学教务管理信息系统",
	"cart.jd.com": "",
	"support.google.com": "某些文件类型被阻止 - Gmail帮助",
	"cashier.95516.com": "银联在线支付-银行卡综合性网上交易转接清算平台！",
	"www.ecampus.fudan.edu.cn": "邯郸东区学生公寓13～16号楼和本部2、3、5、6、7号楼网络资费调整通知",
	"www.packtpub.com": "Mastering Web Application Development with AngularJS | PACKT Books",
	"detail.i56.taobao.com": "物流详情-尚天猫，就购了",
	"d.weibo.com": "发现－热门微博",
	"jproxy.io": "",
	"www.panzz.com": "无法访问 http://www.panzz.com/s/?kw=白色相簿2",
	"jsdo.it": "vox.js でMagicaVoxel作成「しかばね」による「しかばね」ヒエラルキー表示 - jsdo.it - Share JavaScript, HTML5 and CSS",
	"www.12306.cn": "铁路客户服务中心--公 告",
	"subject.tmall.com": "活动导购-尚天猫，就购了",
	"www.ttpod.com": "校园招聘-天天动听招聘中心",
	"luoqi.tiancity.com": "《洛奇Mabinogi》官方网站",
	"docs.google.com": "Redirecting...",
	"lxr.free-electrons.com": "Linux/drivers/net/wireless/iwlwifi/mvm/bt-coex.c - Linux Cross Reference - Free Electrons",
	"compass-style.org": "Compass Help | Compass Documentation",
	"blog.csdn.net": "git 初学解决错误 - 程序员专栏 - 博客频道 - CSDN.NET",
	"fuge.bearychat.com": "复歌科技",
	"www.easyulife.com": "www.easyulife.com|简单你的生活",
	"webmap0.map.bdimg.com": "thumbnails (218×140)",
	"www.115.com": "115，全新的生活方式！",
	"1.1.1.1": "Logged In",
	"www.browsersync.io": "Browsersync Documentation",
	"www.shouji56.com": "侠客风云传圣堂结局怎么达成 圣堂结局达成方法介绍_56手机游戏下载网",
	"www.91danji.com": "《侠客风云传》江天雄大寿彩蛋_91单机游戏网",
	"memory.10years.me": "联系我们",
	"drive.google.com": "Resume - Bold - Google 文档模板",
	"www.euro-pic.eu": "Euro-pic.eu - X-Art - Truth Or Dare - Lexi Belle, Mia Malkova 3.jpg -",
	"detail.tmall.hk": "",
	"creditcard.ccb.com": "信用卡主页_中国建设银行",
	"www.slant.co": "Comments - Hard to install on some distros - Gala - What are the best window managers for Linux? - Slant",
	"fakefish.github.io": "Froot Wars",
	"truth.bahamut.com.tw": "f162c5d5fd860ebaa3844a030136d803.JPG (427×740)",
	"jobs.ele.me": "饿了么招聘",
	"winscp.net": "WinSCP :: WinSCP",
	"www.weilongshipin.com": "营养健康 > 健康美食_卫龙食品",
	"www.cr173.com": "泰拉瑞亚1.3什么装备最厉害 最强武器推荐_西西软件资讯",
	"www.rhodeshouse.ox.ac.uk": "Thank you for your form submission - The Rhodes Scholarships",
	"www.tldp.org": "Single list of HOWTOs",
	"pc.52pk.com": "侠客风云传泡妞详解及其位置攻略指南_52PK单机游戏",
	"account.bilibili.com": "哔哩哔哩弹幕视频网 - ( ゜- ゜)つロ 乾杯~ - bilibili",
	"www.acfun.tv": "",
	"www.intel.com": "Intel® Dual Band Wireless-AC 7260 Plus Bluetooth*",
	"wuyinliangpin.tmall.com": "店内搜索页-无印良品旗舰店-天猫Tmall.com",
	"www.962.net": "时空幻境星星收集全攻略完整页_乐游网",
	"downloadcenter.intel.com": "Intel® Download Center",
	"www.youtube.com": "Chrome Apps Office Hours: Chrome Storage APIs - YouTube",
	"shanghai.baixing.com": "【上海简历|最新求职简历信息】 - 上海百姓网",
	"hr.163.com": "职位搜索",
	"192.168.1.1": ".::中国电信—天翼宽带::.",
	"www.cnki.net": "让罗马融化在台伯河里——莎士比亚悲剧《安东尼与克莉奥佩特拉》人物分析 - 中国学术期刊网络出版总库",
	"jingyan.baidu.com": "拔火罐的好处和坏处_百度经验",
	"algs4.cs.princeton.edu": "Elementary Sorts",
	"play.baidu.com": "夢想歌(TV size) - Suara - 百度音乐盒",
	"map.baidu.com": "百度地图",
	"message.tieba.baidu.com": "",
	"www.3gmfw.cn": "侠客风云传江天雄的秘密 侠客风云传江天雄角色分析_3G免费网",
	"ratewrite.tmall.com": "",
	"www.pc6.com": "鬼泣5卡在提交分数排行榜解决方法 _pc6资讯",
	"git-scm.com": "Git - gitignore Documentation",
	"www.career1.fudan.edu.cn": "﻿复旦大学学生就业信息网",
	"www.microsoft.com": "如何使用微软 Sculpt 触控鼠标 (Sculpt Touch Mouse) | 微软硬件",
	"order.jd.com": "我的京东--我的订单",
	"bugzilla.redhat.com": "Bug 1150593 – Wifi (intel 7260) stops working at random times",
	"fanyi.baidu.com": "百度翻译",
	"blog.163.com": "js 数组排序函数sort - 诚果的日志 - 网易博客",
	"fraserxu.me": "Fraser Xu · Thoughts on life and code.",
	"chromecj.com": "解决“只能通过Chrome网上应用商店安装该程序”的方法 - Chrome插件(谷歌浏览器插件)",
	"khan4019.github.io": "",
	"re.030buy.cc": "萌购 - 前端交互工程师",
	"www.nczonline.net": "NCZOnline - The official website of Nicholas C. Zakas",
	"wallet.google.com": "Google Payments",
	"www.spdb.com.cn": "欢迎光临上海浦东发展银行主页！",
	"www.livecareer.com": "Resume Samples | Free Resume Sample Resource | LiveCareer.com",
	"www.gamefaqs.com": "Why do some people pronounce \"caesar\" as \"kaizar\" - Fallout: New Vegas Message Board for Xbox 360 - GameFAQs",
	"help.github.com": "Which remote URL should I use? - User Documentation",
	"nczonline.us11.list-manage.com": "NCZOnline Newsletter",
	"10.6.0.10": "Dr.COM登陆成功窗",
	"man.chinaunix.net": "文档手册中心 - ChinaUnix.net技术文档手册中心",
	"news.xinhuanet.com": "“魔性”语录走红网络 多人自称“叶良辰”-新华网",
	"www.duitang.com": "堆糖招聘",
	"tbmsg.baidu.com": "",
	"taoquan.taobao.com": "领取结果页面-尚天猫，就购了",
	"imgcandy.net": "ImgCandy - Earn up to 6.00$/1000 views",
	"www.3h3.com": "鬼泣5 正在将得分提交排行榜怎么解决_当游网",
	"www.jz5u.com": "硬盘性能测试CrystalDiskMark 4.1.0 多语言绿色版-软件下载页_JZ5U绿色下载站",
	"imgchili.net": "imgChili » 11361245_510d7604101fb619f055.jpg",
	"www.jspatterns.com": "Index of /book/7",
	"www.facebook.com": "Facebook",
	"cc.bearhk.info": "[MP4/1.1G]X-Art/Teal & Pam-Supermodel Sex-Czech Mate 纯情的捷克爱侣/9月02日官网同步最新1080P 草榴社區 - powered by phpwind.net",
	"www.tmogroup.asia": "About Us - TMO Group Shanghai",
	"niloccemoadcdkdjlinkgdfekeahmflj": "",
	"job.ctrip.com": "",
	"2121ooxx.taobao.com": "首页-21的宅世界-淘宝网",
	"news.creaders.net": "江泽民岌岌可危 出奇兵扳倒“杨家将” - 万维读者网",
	"www.99danji.com": "侠客风云传送蓝婷礼物提升好感度攻略指引_99单机游戏",
	"www.battlenet.com.cn": "为什么我启动星际2 总很慢？ - 论坛 - 《星际争霸II》",
	"sass-lang.com": "File: SASS_REFERENCE — Sass Documentation",
	"r.ele.me": "味千拉面（三号湾店）外卖_味千拉面（三号湾店）菜单|电话_味千拉面（三号湾店）网上订餐 - 上海市国定路315号...饿了么-网上订餐_外卖_饿了么订餐官网",
	"docs.angularjs.org": "https://docs.angularjs.org/tutorial/step_05",
	"www.game333.net": "侠客风云传妹子怎么攻略 妹子攻略方法介绍攻略_游乐园单机",
	"www.ctrip.com": "携程旅行网官网:酒店预订,机票预订查询,旅游度假,商旅管理",
	"trade.jd.com": "",
	"www.sf-express.com": "运单追踪",
	"www.techweb.com.cn": "熊猫TV9月21日测试上线 王思聪奖励优秀主播1000万_TechWeb",
	"recruitment.ctrip.com": "携程旅行网-2016校园招聘",
	"www.jayproxy.com": "Jayproxy.com",
	"cart.taobao.com": "淘宝网 - 我的购物车",
	"cardsonline.spdbccc.com.cn": "浦发银行",
	"editor.servcorp.com.cn": "Umbraco CMS - editor.servcorp.com.cn",
	"plus.google.com": "Google+",
	"mt.sohu.com": "《泰拉瑞亚》1.3昼夜钥匙有什么用 昼夜钥匙攻略详解-搜狐",
	"tagtree.tv": "Tagtree: Our courses",
	"www.amazon.de": "Fossil Umhängetasche Estate Braun (Brown) MBG9091201: Amazon.de: Koffer, Rucksäcke & Taschen",
	"git.fugetech.com": "Dashboard | GitLab",
	"passport.jd.com": "京东-欢迎登录",
	"forum.gamer.com.tw": "【心得】1.3新武器DPS測試 @Terraria 哈啦板 - 巴哈姆特",
	"www.3dmgame.com": "单机游戏_单机游戏下载_单机游戏下载大全中文版下载_3DMGAME_中国第一单机游戏门户",
	"www.fugetech.com": "复歌科技－fugetech",
	"imgstudio.org": "ImgStudio.org|Earn money sharing images",
	"docs.npmjs.com": "",
	"www.tmogroup.com.cn": "关于我们 - 上海探谋网络科技",
	"bbs.duowan.com": "思维窃取怎么就恶心怎么就脏了？-炉石传说-多玩游戏论坛 -",
	"lfkgmnnajiljnolcgolmmgnecgldgeld": "滑动手势: 选项",
	"yun.baidu.com": "",
	"www.hloom.com": "",
	"www.tudou.com": "",
	"securelogin.arubanetworks.com": "External Welcome Page",
	"www.3500.com": "废土2好玩吗|废土2游戏评测：经典游戏的回归 - 统一下载站",
	"www.ruanyifeng.com": "快速排序（Quicksort）的Javascript实现 - 阮一峰的网络日志",
	"www.yxbao.com": "永恒之柱全剧情图文攻略_永恒之柱全图文教程攻略_游戏堡",
	"www.servcorp.com.cn": "",
	"campus.codeschool.com": "",
	"www.downxia.com": "泰拉瑞亚四项修改器|泰拉瑞亚四项修改器 V1.3.0.3 绿色免费版 下载_当下软件园_软件下载",
	"kangax.github.io": "ECMAScript 6 compatibility table",
	"news.smzdm.com": "K480兄弟来了：Logitech 罗技 发布 K380蓝牙键盘、M337蓝牙鼠标_新品_资讯中心_什么值得买",
	"bzclk.baidu.com": "",
	"shang.qq.com": "二维码页面",
	"oj.acmcoder.com": "赛码网 js OJ 在线模拟器",
	"unit.buyer.trade.taobao.com": "已买到的宝贝",
	"es6.ruanyifeng.com": "ECMAScript 6简介 - ECMAScript 6入门",
	"www.baixing.com": "百姓网帮助中心",
	"www.ximalaya.com": "喜马拉雅FM-校园招聘",
	"gulpjs.com": "gulp.js plugin registry",
	"cv.qiaobutang.com": "HR眼中的简历“15宗罪” - 乔布简历",
	"www.urp.fudan.edu.cn:82": "学工管理系统",
	"set3.mail.qq.com": "QQ邮箱",
	"news.163.com": "",
	"productforums.google.com": "Google 网上论坛",
	"mail.qq.com": "QQ邮箱",
	"open.163.com": "TED_网易公开课",
	"www.subom.net": "【黑店狂想曲】Delicatessen.1991.Blu-ray/蓝光原盘简繁字幕 | 中文字幕下载 | 电影字幕 | 外挂字幕 | Sub of Movies.",
	"danji.18183.com": "泰拉瑞亚1.3专家模式是什么 专家模式攻略_18183单机游戏频道",
	"www.vaikan.com": "千万要避免的五种程序注释方式 | 外刊IT评论",
	"accessories.ap.dell.com": "UltraSharp 高端显示器",
	"www.ccb.com": "欢迎访问中国建设银行网站-个人客户",
	"www.jjwxc.net": "《女程序员的日常》江默xi　ˇ第1章ˇ 最新更新:2015-05-14 22:50:00",
	"go.microsoft.com": "MSN Österreich - jetzt mit dem Hotmail-Nachfolger Outlook und Skype",
	"www.bootcss.com": "Bootstrap中文网",
	"www.tongchao.xyz": "www.easyulife.com|简单你的生活",
	"bearychat.com": "BearyChat",
	"www.google-analytics.com": "",
	"sports.sina.com.cn": "详解欧预赛存亡:9队已晋级 荷兰悬 贝尔创奇迹_西班牙_新浪竞技风暴_新浪网",
	"jaikcnhlohebodlpkmjepipngegjbfpg": "Drag and Go Extension Options",
	"weixin.qq.com": "微信，是一个生活方式",
	"www.dropbox.com": "主页 - Dropbox",
	"deerchao.net": "常用正则表达式",
	"nczonline.us11.list-manage2.com": "NCZOnline Newsletter",
	"u.yieldsquare.com": "",
	"zh.moegirl.org": "艦隊Collection:北方棲姬 - 萌娘百科 萬物皆可萌的百科全書",
	"localhost:3000": "BookmarksManager-Options",
	"sc2.163.com": "虚空之遗 - 《星际争霸II》官方网站_全新版本免费开启，全民战翻天！",
	"kyfw.12306.cn": "余票查询 | 客运服务 | 铁路客户服务中心",
	"porno-pirat.ru": "Image Hosting Script",
	"bbs.plu.cn": "【求助】配置还可以的电脑为什么启动星际超慢！ SC2|星际争霸2 虫群之心 -",
	"www.iciba.com": "Comparation是什么意思_Comparation的翻译_音标_读音_用法_例句_爱词霸在线词典",
	"help.steampowered.com": "",
	"alocgmkblfgekpbcaficfadeclcfpamj": "BookmarksManager-Options",
	"www.huxiu.com": "北大清华复旦交大的节操值多少钱？-虎嗅网",
	"unionpaysecure.com": "Please Wait...",
	"www.urp.fudan.edu.cn": "复旦大学URP信息化校园应用系统",
	"forexprod.alipay.com": "支付宝 - 网上支付 安全快速！",
	"imgserve.net": "ImgServe.net | Earn Money Sharing Images",
	"www.dianping.com": "上海 美食,上海 餐厅餐饮,上海 团购,上海生活,优惠券-大众点评网",
	"chromemarks.userecho.com": "Chrome crash with invalid urls / General forum / CMarks",
	"code.google.com": "Issue 56945 - chromium - chrome.bookmarks.update with invalid URL crashes extension - An open-source project to help move the web forward. - Google Project Hosting",
	"huan-lin.blogspot.com": "Huan-Lin 學習筆記: Git Ignore File",
	"www.acmcoder.com": "赛码·在线编程引领者",
	"www.hearthstone.com.cn": "《炉石传说》官方网站_暴雪首款免费休闲卡牌网游",
	"live.bilibili.com": "哔哩哔哩直播 - 今夜，国庆娱乐专场",
	"uchinobh.tmall.com": "店内搜索页-内野邦豪专卖店-天猫Tmall.com",
	"sale.jd.com": "",
	"www.jb51.net": "数据排序谁最快(javascript中的Array.prototype.sort PK 快速排序)_javascript技巧_脚本之家",
	"china-mmm.jp.net": "MMM CHINA - Official Website",
	"www.jd.com": "京东(JD.COM)-综合网购首选-正品低价、品质保障、配送及时、轻松购物！",
	"www.shakespeare-online.com": "Shakespeare's Julius Caesar: Character Introductions",
	"www.cricode.com": "8大排序算法图文讲解 – 快课网",
	"miserupdate.aliyun.com": "",
	"www.sorting-algorithms.com": "Sorting Algorithm Animations",
	"msdn.microsoft.com": "使用 Web 存储以本地方式保存文件 (Windows)",
	"cdn.akamai.steamstatic.com": "",
	"tcashier.jdpay.com": "京东钱包 jdpay.com",
	"xxxscreens.com": "XXXScreens.com - Free Adult Image Hosting",
	"hr.meizu.com": "魅族招聘",
	"www.biligame.com": "游戏中心 www.biligame.com",
	"www.atlassian.com": "Free Mercurial and Git client for Mac and WindowsMercurial and Git client for Mac and Windows | Atlassian",
	"www.msftncsi.com": "无法访问 http://www.msftncsi.com/ncsi.txt",
	"ba.sandbox.fugetech.com": "login",
	"trading.fugetech.com": "Fuge Trading Platform",
	"search.jd.com": "iphone数据线 - 商品搜索 - 京东",
	"wiki.teamfortress.com": "Training Mode - Official TF2 Wiki | Official Team Fortress Wiki",
	"zhuanlan.zhihu.com": "知乎专栏",
	"task.alibench.com": "",
	"192.168.0.60:3000": "Internal Server Error",
	"apache.org": "Welcome to The Apache Software Foundation!",
	"www.ce.cn": "桌游产业呼唤原创品牌_中国经济网――国家经济门户",
	"sexik.name": "",
	"latest-357269.epara.ru": "",
	"www.enotes.com": "Contrast the characters of Octavius Caesar and Mark Antony. What is the major theme of the play Antony and Cleopatra? - Homework Help - eNotes.com",
	"www.algolist.net": "INSERTION SORT (Java, C++) | Algorithms and Data Structures",
	"todomvc.com": "React • TodoMVC",
	"skype.gmw.cn": "Skype简体中文版官方网站-最清晰的免费网络电话",
	"jlgkpaicikihijadgifklkbpdajbkhjo": "Settings",
	"pages.github.com": "GitHub Pages",
	"www.quora.com": "Home - Quora",
	"c7sky.com": "时隔两年，终于把 Chrome 开发者注册费给交上了 | 小影志",
	"search.proquest.com": "Sprachliches zum Seelenschmetterling - ProQuest",
	"www.mxtrf.net": "",
	"www.yhd.com": "网上超市1号店，省力省钱省时间",
	"m.ximalaya.com": "魔都互联网独角兽股权还没分完。爱来不，来！",
	"ba.stagging.miaosuanji.com": "register",
	"store.taobao.com": "店铺浏览-淘宝网",
	"www.longchoudai.com": "隆筹贷–投资安全下的高收益P2P投资理财/网贷金融服务平台",
	"name.renren.com": "",
	"sh.58.com": "【上海租房|上海租房信息】- 上海58同城",
	"www.kanzhun.com": "",
	"career.tencent.com": "首页 | Tencent 腾讯招聘",
	"drops.wooyun.org": "XCode编译器里有鬼 – XCodeGhost样本分析 | WooYun知识库",
	"www.evergrande.com": "恒大集团",
	"zhaopin.meituan.com": "美团网招聘官网",
	"sh.meituan.com": "【上海团购网】上海团购大全_上海团购网站_美团网",
	"www.yiibai.com": "git push - Git教程",
	"www.meituan.com": "【美团网团购】吃喝玩乐好帮手，专业品质团购网",
	"corp.163.com": "",
	"www.163.com": "网易",
	"cv.heeroluo.net": "罗礼权的个人简历 - 高级前端开发工程师 - Senior Frontend Developer",
	"www.sina.com.cn": "新浪首页",
	"web2.qq.com": "",
	"nonfu.me": "解决github报错：src refspec master does not match any Github – 农夫庄园",
	"resumegenius.com": "Free Downloadable Resume Templates | Resume Genius",
	"superuser.com": "All my chrome extension popups show only as small empty boxes - Super User",
	"fr.todoist.com": "Blank Extension popup on Chrome | Todoist Help center",
	"www.iteye.com": "javascript文件 引用外部js文件 - ITeye问答",
	"en.wiktionary.org": "comparation - Wiktionary",
	"groups.google.com": "Google 网上论坛",
	"www.themuse.com": "275 Free Resume Templates You Can Use Right Now",
	"www.resume-now.com": "Free Resume Builder and more career resources",
	"passport.lagou.com": "找工作-互联网招聘求职网-拉勾网",
	"colobu.com": "gulp plugins 插件介绍 | 鸟窝",
	"forum.opencas.org": "常用排序算法之JavaScript实现 - OpenCAS",
	"latest-358925.epara.ru": "",
	"bbs.yingjiesheng.com": "网易(NetEase) - 应届生求职招聘论坛 - Powered by Discuz!",
	"zhangwenli.com": "Wenli Zhang's CV",
	"se.tmzhw.com": "全天24时享受真人美女一对一视频。。。",
	"game.campus.163.com": "网易游戏2016校园招聘_不拼搏，枉少年！",
	"s.yingjiesheng.com": "互联网上市公司2016校园招聘_互联网上市公司招聘_互联网上市公司校园招聘资料_应届生求职网",
	"www.calmer.cn": "卡木科技",
	"www.yingjiesheng.com": "名企2016校园招聘进度表_应届生求职网YingJieSheng.COM",
	"2013.yingjiesheng.com": "",
	"www.ztree.me": "Home [zTree -- jQuery 树插件]",
	"nczonline.us11.list-manage1.com": "NCZOnline Newsletter",
	"rate.taobao.com": "评价成功 - 淘！我喜欢",
	"i.taobao.com": "我的淘宝",
	"widget.weibo.com": "关注按钮-微博",
	"www.endclothing.com": "END. | Globally Sourced Menswear",
	"202.120.227.56:3210": "由Ex Libris的SFX提供",
	"www.soul-plus.net": "[少女騎士団 (大槍葦人)] 同人合集 [17中文/57日文] [2.26G/度娘] [2015/09/02更新]| 实用漫画| 影 - 北+ North Plus - powered by Pu!mdHd",
	"www.5336cf.com": "[少女騎士団 (大槍葦人）] THEPLEASURES OF PRINCESSE | 琉璃神社",
	"www.mddmm.com": "[Hills] 聖ブリュンヒルデ学園 少女騎士団と純白のパンティ 动画 附游戏CG-萌妹Game - 萌爱漫音坊",
	"s.click.taobao.com": "",
	"dongxi.douban.com": "预定包邮】韩国正品代购scratch night view刮夜景刮刮乐世界名胜（豆瓣）",
	"www.jdon.com": "AngularJS教程之三 服务与依赖注入 -解道Jdon",
	"api.baixing.com.cn": "百姓网-开放API",
	"uchinobh.m.tmall.com": "手机天猫店铺首页",
	"angularjs.org": "AngularJS — Superheroic JavaScript MVW Framework",
	"import.github.com": "https://github.com/tanbowensg/DataTableImprovedFilter.git ⇒ tanbowensg/tanbowensg.github.io",
	"www.chiphell.com": "Dell U2414H 评测 - 显示器|Monitor - Chiphell - 分享与交流用户体验的最佳平台",
	"dict.cn": "comparation是什么意思_comparation在线翻译_英语_读音_用法_例句_海词词典",
	"itbbs.pconline.com.cn": "各位有用DELL U2414H显示器的吗？USB3.0口速度正常吗？_DIY综合论坛_太平洋电脑网产品论坛",
	"www.zybang.com": "英语词汇辨义pose a constrast与make a comparation 的区别与所指的情境_百度作业帮",
	"www.52solution.com": "蓝牙3.0和蓝牙4.0有什么区别？蓝牙4.0有哪些特点？- 电子基础知识 - 我爱方案网",
	"blog.renren.com": "海猫最后的真相 结局 全剧情人物分析（剧透慎入）（EP7相关） – 【人人分享-人人网】",
	"piebbs.pconline.com.cn": "【要放毒了，慎入！！！】晒晒新入手Dell U2414H专业级显示器【论坛首测】【内有XX福利图】_最数码科技论坛_太平洋电脑网最数码论坛",
	"wuxizazhi.cnki.net": "忆往昔风华正茂,看今朝豪情满怀——江泽民同志视察中国联合工程公司-《中国工程咨询》2009年第07期-吾喜杂志网",
	"blog.mn886.net": "js数组求和的方法(最高效率)",
	"www.williamlong.info": "12个强大的Chrome插件-月光博客",
	"greybeard.iteye.com": "设置<input type=\"text\">的默认值 - - ITeye技术网站",
	"passport.weibo.com": "Sina Visitor System",
	"www.vccoo.com": "秋招指南 | 2016届毕业入互联网行业，现在再不准备就晚了 - 微口网",
	"www.nltk.org": "Natural Language Toolkit — NLTK 3.0 documentation",
	"hxzj.biligame.com": "幻想战姬—B站首款代理 最美水墨RPG",
	"rj.baidu.com": "WinSCP下载__百度软件中心",
	"www.msn.com": "MSN Österreich - jetzt mit dem Hotmail-Nachfolger Outlook und Skype",
	"school.freekaoyan.com": "复旦大学历史学系研究生导师简介-钱静怡|研招网|研究生招生信息网|研究生考研网",
	"www.panda.tv": "熊猫TV",
	"my.oschina.net": "JS中：json对象数组按对象属性排序 - BuChiCJS的个人页面 - 开源中国社区",
	"store.sonkwo.com": "502 Bad Gateway",
	"ww2.previewx.com": "",
	"webapps2.alwaysdata.net": "Screens",
	"prpops.com": "",
	"www.030buy.net": "萌购",
	"2mdn.info": "",
	"s3.postimg.org": "Footjob_for_My_Boss_but_No_Cumming_mp4_thumbs_2.jpg (180×100)",
	"damimage.com": "DamImage.com|Earn money sharing images",
	"www.scholaradvisor.com": "Cleopatra’s Relationships with Julius Caesar and Mark Antony",
	"bbs.feng.com": "求助双系统时间错乱问题 - Mac综合讨论区 - 威锋论坛 - 威锋网",
	"verano.buick.com.cn": "威朗 VERANO",
	"www.thefreedictionary.com": "Comparation - definition of Comparation by The Free Dictionary",
	"www.highcharts.com": "Interactive JavaScript charts for your webpage | Highcharts",
	"www.w3cplus.com": "sass入门 - sass教程",
	"books.google.com": "",
	"epub.cnki.net": "检索—中国知网",
	"onclickads.net": "Redirect",
	"10years.me": "十年后",
	"linux.chinaunix.net": "Linux Chinese HOWTO 中文版 - 技术文档 - 桌面应用 Linux时代 - 开源、自由、共享 - 中国最大的Linux技术社区",
	"roclinux.cn": "休息五分钟，学几个bash快捷键 | Linux大棚",
	"www.ithome.com": "终于把P2P、P2C 、O2O 、B2C、B2B、C2C弄清楚了 - P2P,O2O,C2C,B2C - IT之家",
	"uule.iteye.com": "JS中的call()和apply()方法 - 每天进步一点点！ - ITeye技术网站",
	"www.china.com.cn": "英国媒体:科学家们设计出一套七分钟快速健身法_中国网",
	"www.cidu.com.cn": "医院2014中秋节放假通知，2014年中秋节医院如何放假_中秋节放假",
	"sh.fang.com": "【上海房地产门户|上海房地产网】- 上海搜房网 房天下",
	"www.gbtags.com": "54341的标签:【datatables】 极客标签 | 在线编程知识分享学习平台",
	"datatables.net": "Plug-ins",
	"www.ecma-international.org": "ECMAScript Language Specification - ECMA-262 Edition 5.1",
	"hax.iteye.com": "JavaScript语句后应该加分号么？ - hax的技术部落格 - ITeye技术网站",
	"easyabc.95599.cn": "中国农业银行公共客户版",
	"eapply.abchina.com": "申请e站_中国农业银行",
	"www.abchina.com": "中国农业银行",
	"bbs.kafan.cn": "大家帮我看看，是不是中毒了，还是卡巴的误报，谢谢了_卡巴斯基_反病毒区 卡饭论坛 - 互助分享 - 大气谦和!",
	"wenda.haosou.com": "开机跳出“c：\\\\decuments ...\\\\funkoala.dlls时出错。找不到指定程序”。_好搜问答",
	"winfiledb.com": "How to fix FunKoala.dll error, what is FunKoala.dll? [0309033]",
	"www.kafan.cn": "funkoala.dll错误 - 卡饭教程",
	"www.cybespoke.com": "Cybespoke",
	"shanghai.liebiao.com": "【顺丰复旦大学代办点】_上海列表网",
	"blog.sina.com.cn": "HTTP 错误 405 解决办法_lwx720318_新浪博客",
	"zhannei.baidu.com": "上海顺丰快递复旦大学代办点_百姓网信息搜索站内搜索",
	"www.gamesradar.com": "Braid Star Guide | GamesRadar",
	"braid.wikia.com": "Stars - Braid Wiki",
	"favorite.shopmodule.jaeapp.com": "内野邦豪专卖店 - 收藏有礼",
	"h5.m.taobao.com": "评价下载页",
	"blog.teamtreehouse.com": "Using GitHub Pages To Host Your Website - Treehouse Blog",
	"t12.baidu.com": "403 Forbidden",
	"bbs.a9vg.com": "鬼泣5和生化危机6二周目的感想 - 鬼泣 - A9VG电玩部落论坛",
	"bbs.tianya.cn": "值得程序员一看的it文学书籍(转载)_程序员_天涯论坛",
	"www.zhouhua.info": "深入了解javascript的sort方法 | Step Over",
	"www.dell.com.cn": "Dell - 戴尔官方网站 | Dell 中国大陆",
	"erogamescape.ddo.jp": "COW Proxy",
	"bbs.tgbus.com": "【批评空间】历代GALGAME综合集计排行TOP 100(TOP100~1榜单更新完成，榜单文本放出) - AVG游戏综合讨论区 - 电玩巴士游戏论坛",
	"sh.lanfw.com": "上海人才公寓",
	"ednigddfbelnfidmlkdmflhifhhkoggg": "BookmarksManager-Options",
	"toutiao.sogou.com": "",
	"subom.net": "中文字幕下载 | 字幕下载 | 电影字幕 | 外挂字幕 | Sub of Movies.",
	"www.urp.fudan.edu.cn:78": "复旦教务管理系统",
	"uis1.fudan.edu.cn": "复旦大学统一身份认证服务",
	"www.washingtontimes.com": "Washington Times - Politics, Breaking News, US and World News",
	"codex.wordpress.org": "Function Reference/get page by title « WordPress Codex",
	"www.clanfei.com": "jQuery中利用JSONP解决AJAX跨域问题 - 蓝飞技术部落格 —— 关注前沿，追求卓越。",
	"www.okhqb.com": "TENGA飞机杯如何拆卸清洗，让爱崭新如初",
	"api.jquery.com": "jQuery.ajax() | jQuery API Documentation",
	"www.gdyfs.com": "《泰拉瑞亚》1.3部分新武器、道具及旗帜图文介绍|柱子|掉落|召唤_云浮在线",
	"www.pipaw.com": "泰拉瑞亚四柱怎么打 四柱之星辰之柱打法及掉落材料介绍-琵琶网",
	"www.ptt.cc": "[遊戲] Terraria 1.3改版心得 - 看板 Steam - 批踢踢實業坊",
	"m.yxzoo.com": "泰拉瑞亚邪教信徒boss介绍 邪教信徒怎么召唤_泰拉瑞亚_游戏园手机版",
	"imgcream.com": "ImgCream » Image Viewer",
	"forums.terraria.org": "Centurion | Terraria Community Forums",
	"www.yunshipei.com": "首页 | 云适配 - 中国最大的HTML5企业移动应用平台",
	"my.tv.sohu.com": "泰拉瑞亚--大战(?)机械蠕虫-原创视频-搜狐视频",
	"baidu.aipai.com": "泰拉瑞亚打机械蠕虫（上）_高清在线观看_百度视频",
	"v.baidu.com": "",
	"www.aipai.com": "泰拉瑞亚教程：机械蠕虫 毁灭者 - 泰拉瑞亚视频 - 爱拍原创",
	"ol.tgbus.com": "泰拉瑞亚pe装备套防御排名前4的是什么？ - 新闻中心 - 电玩巴士",
	"yepnopejs.com": "yepnope.js | A Conditional Loader For Your Polyfills!",
	"mrantifun.net": "MrAntiFun, PC Video Game Trainers ,Cheats and mods",
	"localhost:3001": "Browsersync",
	"bbs.ptbus.com": "泰拉瑞亚百科——Boss大全_口袋巴士论坛_骑士经理 像素 - 口袋巴士论坛 - 口袋巴士_手机游戏玩家第一论坛",
	"blog.yfeil.com": "泰拉瑞亚(Terraria)v1.3.0.8汉化v3.3 - 戳破蜘蛛网",
	"play.163.com": "《英雄传说空之轨迹FC：改HD版》追加内容公开_网易游戏频道",
	"119.147.99.45": "",
	"gist.github.com": "Gulp常用插件",
	"waimaichaoren.com": "上海网上订餐_饿了轻松点外卖_外卖超人",
	"codeable.io": "Codeable - Speed up your theme development with Gulp",
	"ohboard.com": "Chrome Web App Development Guide | OhBoard",
	"surveys.jd.com": "京东在线支付-用户反馈调查",
	"www.orsoon.com": "炉石传说奥术冲击攻略 奥术冲击卡牌属性详解_未来软件园文章",
	"www.yesky.com": "Linux的窗口管理器 _天极网",
	"webcache.googleusercontent.com": "Slow wifi on Fedora : Fedora",
	"ask.fedoraproject.org": "wifi connection problem - Ask Fedora: Community Knowledge Base and Support Forum",
	"www.sourcetreeapp.com": "Download SourceTree for free",
	"www.techradar.com": "10 of the best Linux window managers | TechRadar",
	"www.engadget.com": "How-to: Picking a Window Manager in Linux",
	"www.degraeve.com": "IMG2TXT: ASCII Art Made Easy!",
	"exmail.qq.com": "腾讯企业邮箱，用心你看得见 - 热线：400-100-3366",
	"pub.creaders.net": "COW Proxy",
	"click.union.jd.com": "京东网上商城",
	"zhan.renren.com": "ASCII Art --- 字符画，在线生成工具 — 人人小站",
	"www.aswifter.com": "Swift 实现图片转字符画的功能 | APP开发者",
	"www.network-science.de": "ASCII Generator",
	"ruby-china.org": "社区的字符画是用什么生成的 » 社区 » Ruby China",
	"www.epinv.com": "图片转字符画软件_ASCII Generator 2.0 绿色中文单文件版_亿品绿色软件下载",
	"m.100bt.com": "【橙子】那些年、有爱的字符画_奥比岛粉丝圈_手机百田网",
	"fallout.answers.wikia.com": "Is Caesar pronounced \"See-sar\" or \"Kay-zar\"? - Fallout Answers",
	"sc.sina.com.cn": "青岛天价虾被关停一只虾38元 烧烤店涉嫌误导消费者_新浪四川_新浪网",
	"www.sephora.cn": "【博士】价格-博士化妆品-HUGOBOSS博士-SEPHORA丝芙兰官网",
	"www.ihuochaihe.com": "火柴盒-发现打动人心的事物",
	"baidu.waimai.com": "无法访问 http://baidu.waimai.com/",
	"join.dianping.com": "招聘首页",
	"www.amazon.co.jp": "Amazon.co.jp: 在中国受欢迎的母婴用品: ベビー＆マタニティ",
	"e-intuit.hk": "Welcome to visit E-Intuit Limited",
	"cart.tmall.com": "我的购物车 - 天猫超市 - 天猫Tmall.com - 上天猫，就购了-尚天猫，就购了",
	"chaoshi.tmall.com": "天猫超市-天猫Tmall.com-上天猫，就购了-尚天猫，就购了",
	"getpocket.com": "Pocket: 登录",
	"download.csdn.net": "(精通AngularJS)Mastering Web Application Development with AngularJS code 源代码 - 下载频道 - CSDN.NET",
	"www.dangshopex.com": "CSS3:nth-child()伪类选择器，Table表格奇偶数行定义样式_美图美文欣赏|创意设计欣赏|网站界面设计|设计师网址导航|个人展示-爱设计网",
	"wireless.wiki.kernel.org": "en:users:drivers:iwlwifi [Linux Wireless]",
	"davidwalsh.name": "Event Delegation",
	"zhiyou.smzdm.com": "系统消息 | 什么值得买",
	"union.click.jd.com": "京东网上商城",
	"test.smzdm.com": "雷柏KX 无线双模式 背光机械键盘（轴体颜色随机）_消费众测_什么值得买",
	"www.ithao123.cn": "Fedora 19下安装无限网卡驱动（Intel Corporation Wireless 7260 (rev 73)）_IThao123 - IT行业第一站",
	"forum.ubuntu.org.cn": "Intel wireless-ac 7260在ubuntu下找不到驱动 - 查看主题 • Ubuntu中文论坛",
	"history.fudan.edu.cn": "钱静怡",
	"eternity.obsidian.net": "Pillars of Eternity",
	"faxian.smzdm.com": "限S码：DIESEL 男士平角内裤 3条装 20.5美元_美国亚马逊优惠_发现频道_什么值得买",
	"s4.postimg.org": "",
	"www.buzhixiangqin.com": "服务单身,不止相亲",
	"elearn.sbg.ac.at": "Blackboard Learn",
	"106.3.36.25": "",
	"react-china.org": "React 中文",
	"www.aliexpress.com": "AliExpress.com - Online Shopping for Electronics, Fashion, Home & Garden, Toys & Sports, Automobiles from China.",
	"arch.pconline.com.cn": "《武林群侠传》“揭发江天雄”事件攻略　[游戏攻略]",
	"www.anxia.com": "侠客风云传武器流派分析|侠客风云传武器流派分析 武器有何对应打法和路线_单机攻略_安下软件站",
	"wulin.bbs.fhyx.com": "江天雄是好人了吗？ - 武林茶楼 - 侠客风云传 - Powered b",
	"huaban.com": "采集到花瓣",
	"www.liaoxuefeng.com": "忽略特殊文件 - 廖雪峰的官方网站",
	"yijiebuyi.com": ".gitignore设置 git忽略跟踪文件和文件夹 一介布衣",
	"img1.gamersky.com": "image033.jpg (1000×562)",
	"sorting.at": "SORTING",
	"news.52pk.com": "《侠客风云传》DLC情报疑曝光 或将于九月发布_52pk新闻中心",
	"comic.52pk.com": "内涵漫画：复联2手办恶搞(1)_动漫频道内涵漫画_comic.52pk.com",
	"cfhdojbkjhnklbpkdaibdccddilifddb": "Adblock Plus Options",
	"glyphicons.com": "Sharp and clean symbols - GLYPHICONS.com",
	"www.k73.com": "侠客风云传各角色喜好物品礼物列表 _k73电玩之家",
	"games.newhua.com": "《侠客风云传》玩法要点及实用小技巧总结 - 牛华网",
	"www.youxicheng.net": "【侠客风云传天书】天书怎么获得_天书获得方法详解_游戏城",
	"less.bootcss.com": "快速入门 | Less.js 中文文档",
	"mofang.ruanmei.com": "软媒魔方官网 - 新一代优化大师，支持Win10、Win8.1、Win7、Windows XP，软媒魔方6.12最新正式版下载",
	"product.yesky.com": "【宏碁Aspire V Nitro】(Acer Aspire V Nitro)报价_图片_参数_评测_论坛_宏碁Aspire V Nitro笔记本报价-天极产品库",
	"www.lek.com": "Consulting Firm, Management Consulting Firms, Consulting Firms",
	"m.sh.happyvalley.cn": "上海欢乐谷、玛雅海滩水公园手机官方网站",
	"sh.happyvalley.cn": "上海欢乐谷|上海欢乐谷官方网站",
	"agar.io": "Agar.io",
	"aj.44doors.com": "AJ",
	"www.6pm.com": "Ted Baker Rtivo Black Shine - 6pm.com",
	"www.nydus2015.info": "NydusVPN » 最专业的VPN提供商,高速稳定无限流量 -【正品官网】",
	"www.92af.com": "AF论坛_AF官网海外代购网站",
	"www.nydus.info": "错误: 您所请求的网址（URL）无法获取",
	"angularjs.cn": "AngularJS中文社区",
}